In [16]:
# Min-max normalization
import pandas as pd
import numpy as np
df=pd.read_csv("/Users/jaeeponde/IML_A1/IML_A1/Regression_Task/data/training_data.csv")
df


# Display the normalized dataframe

MAKE  VEHICLE CLASS  ENGINE SIZE  CYLINDERS  COEMISSIONS  FUEL_X  FUEL_Z  \
0    3.00           3.08          2.0          4          228       1       0   
1    4.75           4.34          4.7          8          382       1       0   
2    4.50           4.34          4.8          8          373       1       0   
3    4.00           4.34          4.6          8          380       1       0   
4    4.00           4.34          4.2          6          359       1       0   
..    ...            ...          ...        ...          ...     ...     ...   
506  3.75           4.50          4.3          6          350       1       0   
507  3.75           4.34          4.3          6          386       1       0   
508  4.00           3.42          3.0          6          267       1       0   
509  3.50           3.02          2.3          4          246       0       1   
510  3.75           4.83          5.7          8          426       1       0   

     TRANSMISSION_A4  TRANSMISSION_A5  TRANSMISSION_M5  FUEL CONSUMPTION  
0                  0                0                1              11.2  
1                  0                0                1              18.8  
2                  0                0                1              18.9  
3                  1                0                0              18.5  
4                  1                0                0              17.3  
..               ...              ...              ...               ...  
506                1                0                0              17.0  
507                0                0                1              18.7  
508                1                0                0              13.6  
509                0                0                1              12.6  
510                1                0                0              20.6  

[511 rows x 11 columns]

In [17]:
df_train=df.drop(columns=['FUEL CONSUMPTION'])

In [18]:
df_normalized = (df_train - df_train.min()) / (df_train.max() - df_train.min())

In [19]:
df_normalized['FUEL CONSUMPTION'] = df['FUEL CONSUMPTION'].values
df_normalized

MAKE  VEHICLE CLASS  ENGINE SIZE  CYLINDERS  COEMISSIONS  FUEL_X  \
0    0.071429       0.048913     0.142857   0.111111     0.317136     1.0   
1    0.571429       0.733696     0.528571   0.555556     0.710997     1.0   
2    0.500000       0.733696     0.542857   0.555556     0.687980     1.0   
3    0.357143       0.733696     0.514286   0.555556     0.705882     1.0   
4    0.357143       0.733696     0.457143   0.333333     0.652174     1.0   
..        ...            ...          ...        ...          ...     ...   
506  0.285714       0.820652     0.471429   0.333333     0.629156     1.0   
507  0.285714       0.733696     0.471429   0.333333     0.721228     1.0   
508  0.357143       0.233696     0.285714   0.333333     0.416880     1.0   
509  0.214286       0.016304     0.185714   0.111111     0.363171     0.0   
510  0.285714       1.000000     0.671429   0.555556     0.823529     1.0   

     FUEL_Z  TRANSMISSION_A4  TRANSMISSION_A5  TRANSMISSION_M5  \
0       0.0              0.0              0.0              1.0   
1       0.0              0.0              0.0              1.0   
2       0.0              0.0              0.0              1.0   
3       0.0              1.0              0.0              0.0   
4       0.0              1.0              0.0              0.0   
..      ...              ...              ...              ...   
506     0.0              1.0              0.0              0.0   
507     0.0              0.0              0.0              1.0   
508     0.0              1.0              0.0              0.0   
509     1.0              0.0              0.0              1.0   
510     0.0              1.0              0.0              0.0   

     FUEL CONSUMPTION  
0                11.2  
1                18.8  
2                18.9  
3                18.5  
4                17.3  
..                ...  
506              17.0  
507              18.7  
508              13.6  
509              12.6  
510              20.6  

[511 rows x 11 columns]

In [20]:
df_shuffled = df_normalized.sample(frac=1, random_state=42).reset_index(drop=True)
train_size = 511 - 50  # 461 for training
train_data = df_shuffled.iloc[:train_size]
test_data = df_shuffled.iloc[train_size:]

# Extract features and target
X_train = train_data.drop(columns='FUEL CONSUMPTION').values
y_train = train_data['FUEL CONSUMPTION'].values
X_test = test_data.drop(columns='FUEL CONSUMPTION').values
y_test = test_data['FUEL CONSUMPTION'].values

In [21]:
import numpy as np
X_train_biased = np.c_[np.ones(X_train.shape[0]), X_train]
X_test_biased = np.c_[np.ones(X_test.shape[0]), X_test]

In [22]:
X_train_biased

array([[1.        , 0.21428571, 0.04891304, ..., 0.        , 0.        ,
        1.        ],
       [1.        , 0.        , 0.23369565, ..., 1.        , 0.        ,
        0.        ],
       [1.        , 0.35714286, 0.04891304, ..., 0.        , 0.        ,
        1.        ],
       ...,
       [1.        , 0.21428571, 0.04891304, ..., 0.        , 0.        ,
        1.        ],
       [1.        , 0.14285714, 0.04891304, ..., 1.        , 0.        ,
        0.        ],
       [1.        , 0.21428571, 0.33695652, ..., 1.        , 0.        ,
        0.        ]])

In [23]:
y_train

array([13. , 13.3, 11.1, 14.9, 13.1, 16.3, 12.3, 11.7, 11.7, 15.2, 14.4,
       13.6, 10.3, 12.2, 13.3, 15.5, 22.3, 12.9, 11.3, 10.9, 15.5, 15. ,
       14.6, 11.7, 19.6, 18.8, 12.2, 12.5, 13.2, 15.2, 13.1, 16.7,  9.8,
       18.5, 15.2, 13.2, 19.3, 12.5, 11.4, 16.2, 19.9, 13.2, 16.3, 13.5,
       12.1, 13.5, 13.4, 18.3, 18.9, 10. , 14.4, 18.6, 13.8, 12.8, 19.4,
        9.8, 21.4, 12.6, 14.5, 13.7, 10.5, 13.2, 11.4,  9.1, 10.6, 16.8,
       11.2, 13.5, 20.6, 13.1,  7.1, 14.9, 10.3, 12.5, 14.9, 15.9, 12.5,
       13.6, 12.1, 13.6, 19.6, 15. , 13. , 10.6, 16.6, 11.7, 15.2, 13.8,
       16.1, 17.3, 11.8, 17.8, 11.9, 15.5, 11.6, 17.3, 14.3, 17. , 17.7,
       10.8, 11.3, 21.8, 15.1, 15.2, 12.9, 18.5, 15.7, 17.8, 14.2, 15.4,
       13.8, 16.4, 16.5, 11.9, 11.8, 20.2, 15.4, 11.8, 15.2, 14.5, 18.3,
       16.5, 16.2, 18.2, 20. , 16.6, 18.9, 26.3, 17. , 13.9, 14.5, 16.2,
       11.2, 15.6, 17.7, 11.2, 12.7, 16.2, 20.1,  7.6, 13.5, 15.7, 21.8,
       14. , 17.2, 13.7, 18.7, 21.6, 13.6, 15.9, 18

In [43]:
weights = np.full(X_train.shape[1], 4.0)  # Random initialization
learning_rate = 0.001  # Set your learning rate
n_iterations = 1000  # Number of iterations for gradient descent

In [44]:
weights

array([4., 4., 4., 4., 4., 4., 4., 4., 4., 4.])

In [45]:
def gradient_descent(X, y, weights, learning_rate, n_iterations):
    n_samples = len(y)

    for _ in range(n_iterations):
        
        # Compute the predictions
        predictions = X.dot(weights)
        
        # Compute the gradient
        gradients = (2/n_samples) * X.T.dot(predictions - y)
        
        # Update the weights
        weights -= learning_rate * gradients

        print("current weights \n")
        print(weights)
        
    return weights

In [46]:
weights = gradient_descent(X_train, y_train, weights, learning_rate, n_iterations)


current weights 

[4.00000373 3.99969419 3.999997   4.00003373 4.00009599 3.99953401
 4.0005526  3.99970378 4.00001222 3.99979088]
current weights 

[4.0000077  3.99938885 3.99999429 4.0000677  4.00019244 3.99906914
 4.00110497 3.99940825 4.00002436 3.99958209]
current weights 

[4.00001191 3.99908396 3.99999187 4.00010191 4.00028934 3.9986054
 4.0016571  3.99911342 4.0000364  3.99937362]
current weights 

[4.00001636 3.99877953 3.99998975 4.00013636 4.00038669 3.99814279
 4.00220901 3.99881926 4.00004836 3.99916549]
current weights 

[4.00002104 3.99847555 3.99998791 4.00017105 4.00048449 3.99768129
 4.00276069 3.9985258  4.00006022 3.99895769]
current weights 

[4.00002596 3.99817203 3.99998637 4.00020597 4.00058274 3.99722091
 4.00331213 3.99823301 4.00007199 3.99875021]
current weights 

[4.00003111 3.99786897 3.99998511 4.00024114 4.00068143 3.99676164
 4.00386335 3.99794091 4.00008367 3.99854305]
current weights 

[4.0000365  3.99756635 3.99998414 4.00027654 4.00078057 3.99630349

In [47]:
def predict(X, weights):
    return X.dot(weights)

# Predictions
y_train_pred = predict(X_train, weights)
y_test_pred = predict(X_test, weights)

In [48]:
def mean_squared_error(y_true, y_pred):
    return np.mean((y_true - y_pred) ** 2)

# Evaluate on training data
train_mse = mean_squared_error(y_train, y_train_pred)
print(f'Training MSE: {train_mse}')

# Evaluate on testing data
test_mse = mean_squared_error(y_test, y_test_pred)
print(f'Testing MSE: {test_mse}')

Training MSE: 2.7017675349596124
Testing MSE: 2.144721205717727


In [49]:
import pandas as pd

# Assuming y_train, y_train_pred, y_test, and y_test_pred are NumPy arrays

# Create a DataFrame for training data comparison
df_train_comparison = pd.DataFrame({
    'y_train_actual': y_train,
    'y_train_predicted': y_train_pred
})



# Optionally, display them side by side (optional, can display each separately as well)
print("Training Data Comparison:")
df_train_comparison

Training Data Comparison:


y_train_actual  y_train_predicted
0              13.0          12.667110
1              13.3          12.820994
2              11.1          11.561120
3              14.9          15.103363
4              13.1           9.276989
..              ...                ...
456             8.2           9.915306
457            15.2          17.099919
458            10.2          10.793455
459            11.8          11.012107
460            13.9          12.845736

[461 rows x 2 columns]

In [50]:
import pandas as pd

# Assuming y_train, y_train_pred, y_test, and y_test_pred are NumPy arrays


# Create a DataFrame for testing data comparison
df_test_comparison = pd.DataFrame({
    'y_test_actual': y_test,
    'y_test_predicted': y_test_pred
})

# Optionally, display them side by side (optional, can display each separately as well)
print("Testing Data Comparison:")
df_test_comparison

Testing Data Comparison:


y_test_actual  y_test_predicted
0            15.0         16.782567
1            19.3         18.589344
2            13.2         13.809419
3            12.7          7.302221
4            15.0         14.570727
5            15.5         16.716951
6            15.7         16.123021
7            18.7         17.883187
8            13.4         13.644473
9            15.2         17.403563
10           18.1         18.677836
11           17.7         16.090843
12           13.2         12.746183
13           14.0         12.670043
14           22.1         21.080100
15            8.8          9.368001
16           12.2         13.469655
17            9.6          9.571084
18           15.4         16.561625
19           17.8         18.907104
20           13.0         13.674995
21           12.0         10.422356
22           14.7         15.986309
23           21.4         20.279610
24           14.4         12.477701
25           17.8         18.247908
26           13.9         12.781484
27           13.2         13.809419
28           10.9         10.426461
29           14.2         10.393792
30           14.2         14.101006
31           15.2         14.619657
32           14.3         14.734737
33           13.8         14.498218
34           10.6         10.830717
35           18.9         18.705002
36           16.2         16.220633
37           12.1         14.484510
38           13.4         11.000804
39           16.3         18.141164
40           13.8         13.799302
41           20.6         21.020190
42           11.8         11.171852
43           13.8         13.349805
44           19.3         19.491932
45           14.9         17.326116
46           18.7         18.048590
47           16.8         18.300093
48           12.5         10.518385
49           10.6         11.517323